### PR TITLE
So how to retrieve yahoo search results

### PR DESCRIPTION
**Pull request by chukhraiartur**
For checking

### CODE REVIEW

**Review by dimitryzub — COMMENTED** [review]
Hi, @chukhraiartur 👋

Almost everything looks good, I added a few changes. Apply them, commit and push them to update changes.

A few things to point out: 
1. PR name for the future. `<platform>:<question_name>`: `Stackoverflow: how to retrieve yahoo search results`
2. take a look at the screenshot and `bs4` vs `parsel` examples that explicitly show that even if you use the same selectors, the actual output will be different.
3. try to always provide examples that will be easier for people to understand and remove possible reader questions right away.

Good job 👍

**Comment by chukhraiartur** [comment]
@dimitryzub, I made the changes you mentioned above. What do you say? 🤔

**Review by dimitryzub — APPROVED** [review]
@chukhraiartur Looks good  👍 You can go ahead and publish it on Stackoverflow.

One thing you forget is to add your SerpApi `API_KEY` on replit under Secrets (Environment Variables): so users can test SerpApi solution on replit: 

image

**Comment by chukhraiartur** [comment]
Link to the answer -> https://stackoverflow.com/a/71737496/18597245

**Pull request merged**
